version: '3.8'

name: g1-project
services:
  postgres:
    image: postgres:16-alpine
    container_name: g1-db
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - g1-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - g1-net

  # backend:
  #   build: ./TBackend
  #   container_name: g1-backend
  #   ports:
  #     - ${PORT}:${PORT}
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #   depends_on:
  #     - postgres
  #   networks:
  #     - g1-net
  #   env_file:
  #     - ./.env
    
    

  # frontend:
  #   container_name: g1-frontend
  #   build: ./TProject
  #   ports:
  #     - 5173:5173
  #   networks:
  #     - g1-net
  #   depends_on:
  #     - backend
  #   environment:
  #    - CHOKIDAR_USEPOLLING=true
  #    - VITE_HOST=0.0.0.0  # Add this line

volumes:
  g1-data:

networks:
  g1-net:
    # aliases:
    #   - g1-db  
