name: g1-project # You can also change this to another name to avoid warning with existing group. 
services:
  frontend:
    container_name: g1-frontend
    build: .
    ports:
      - 3333:5173
    networks:
      - g1-net
    depends_on:
      - http://localhost:3000
    environment:
     - CHOKIDAR_USEPOLLING=true
networks:
  g1-net: # Check by using `docker network ls` command
