name: shopping
services:
  postgres:
    image: postgres:16-alpine
    container_name: g1-db
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - g1-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - g1-net
volumes:
  g1-data:
networks:
  g1-net:
